name: geokavach
description: "Dhule Satellite Cadastral RTK & Partition System"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

flutter:
  uses-material-design: true
