name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Create Android Project & Build Release APK
        run: |
          flutter create . --platforms=android
          flutter build apk --release

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: geokavach-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
